### ISSUE TITLE
Call to undefined method rmrevin\yii\fontawesome\component\Icon::transform()

### ISSUE THREAD

**Issue by paskuale75** [simialbi/yii2-ticket#11]
in /var/www/html/my-app/app/modules/ticket/views/ticket/index.phpat line 286

**Comment by simialbi** [comment]
use [simialbi/yii2-fontawesome](https://github.com/simialbi/yii2-fontawesome) in `composer.json` instead of `rmrevin/yii2-fontawesome` (it's a replacement).

**Comment by paskuale75** [comment]
Many thanks @simialbi solved but now I've new problem
The file or directory to be published does not exist: /var/www/html/my-app/vendor/fortawesome/font-awesome-pro ....

**Comment by paskuale75** [comment]
Added it, but.... composer update told me -> nothing to install, update or remove

**Comment by paskuale75** [comment]
my composer.json (require section)

```
.....
"fortawesome/font-awesome": "^5.12.0","simialbi/yii2-kanban": "^2.0.0",
"simialbi/yii2-ticket": "*",
"simialbi/yii2-summernote": "*",
....

```

but it keeps giving me the same error message!

**Comment by simialbi** [comment]
It should work with `simialbi/yii2-fontawesome` additional included...

**Comment by paskuale75** [comment]
what version ? Thanks

**Comment by simialbi** [comment]
`^3.4.8`

**Comment by paskuale75** [comment]
Great @simialbi now it works like a charme !!!
