### ISSUE TITLE
assign ticket more one people

### ISSUE THREAD

**Issue by paskuale75** [simialbi/yii2-ticket#17]
Hi @simialbi possible to assign a ticket to more people ?

**Comment by simialbi** [comment]
Not now

**Comment by paskuale75** [comment]
can i try and do a PR or were you already planning ?

**Comment by simialbi** [comment]
I don't see the reason why?

**Comment by paskuale75** [comment]
isn't that a possible scenario? Can I have a ticket that is so heavy to carry out that it can be assigned to more than one person ? if not ok, we can close this issue ;)

**Comment by simialbi** [comment]
You can reassign a ticket. But if you really need more than one person on a ticket, you should create a kanban task and assign the other persons to the task. There is still a person needed who has the lead...
